jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        settings-path: ${{ github.workspace }}
    - continue-on-error: true
      name: compile and test
      run: mvn compile test --file pom.xml
    - continue-on-error: true
      name: build source code
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
      name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
name: publish
on:
  repository_dispatch:
    types: trigger-ga___maven-publish.yml
