jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: compile and test
      run: mvn compile test --file pom.xml
    strategy:
      matrix:
        java:
        - '16'
name: test
on:
  repository_dispatch:
    types: trigger-ga___maven-test.yml
